/*!
 * UA Detector
 * Device brand detect - v0.1.0 (2014-09-24T09:15:12+0800)
 * Released under LGPL license
 */

var util = require('./util'), os = require('./os');


var appleRules =[
	{ name: 'iPad', rule: /iPad/ },
	{ name: 'iPod', rule: /iPod/ },
	{ name: 'iPhone', rule: /iPhone/ },
	{ name: 'iPhone', rule: /\biPh OS\b/ }
];

var otherRules = [
	{ name: '三星', rule: /\bSAMSUNG\b/i },
	{ name: '三星', rule: /\bGalaxy/i },
	{ name: '摩托罗拉', rule: /\bMotorola(?:\b|_)/i },
	{ name: '小米', rule: /\bXiaoMi(?:\b|_|\d)/i },
	{ name: '魅族', rule: /\bMEIZU(?:\b|_)/i },
	{ name: '诺基亚', rule: /\b(?:NOKIA|Lumia)(?:\b|_)/i },
	// { name: '果冻', rule: /\bGoDonie(?:\b|_)/i },
	// { name: '现代', rule: /\bHYUNDAI(?:\b|_)/ },
	// { name: '七彩虹', rule: /\bColorfly(?:\b|_)/ },
	// { name: '斐讯', rule: /\bPHICOMM(?:\b|_)/i },
	// { name: '聆韵', rule: /\bLingwin[A-Z]\d+\b/ },
	// { name: '聆韵', rule: /\bLINGWIN(?:\b|_)/i },
	// { name: '万事通', rule: /\bMASTONE(?:\b|_)/ },
	// { name: '读书郎', rule: /\bReadboy(?:\b|_)/i },
	// { name: '优购', rule: /\bUOOGOU(?:\b|_)/ },
	// { name: '富可视', rule: /\bInFocus\b/ },
	{ name: '欧博信', rule: /\bOPSSON(?:\b|_)/ },
	// { name: '本为', rule: /\bBenWee(?:\b|_)/ },
	// { name: '凯利通', rule: /\bKliTON(?:\b|_)/i },
	// { name: '万利达', rule: /\bMALATA(?:\b|_)/ },
	// { name: '大唐', rule: /\bDATANG(?:\b|_)/ },
	{ name: '天语', rule: /\bK[-\s]?Touch(?:\b|_|[A-Z])/i },
	// { name: '天时达', rule: /\bTELSDA(?:\b|_)/ },
	// { name: '诺亚信', rule: /\bNOAIN(?:\b|_)/ },
	// { name: '唯乐', rule: /\bvollo(?:\b|_)/ },
	// { name: '米蓝', rule: /\bMLLED(?:\b|_)/ },
	// { name: '脉腾', rule: /\bMytel(?:\b|_)/i },
	// { name: '易派', rule: /\bepade(?:\b|_)/ },
	// { name: '德赛', rule: /\bDESAY(?:\b|_)/ },
	// { name: '明泰', rule: /\bMinte(?:\b|_)/ },
	// { name: 'E派', rule: /\bEBEST(?:\b|_)/ },
	// { name: '优赛', rule: /\bIUSAI(?:\b|_)/ },
	// { name: '卓酷', rule: /\bZUOKU(?:\b|_)/ },
	// { name: '邦华', rule: /\bBOWAY(?:\b|_)/ },
	{ name: '海尔', rule: /\bHaier(?:\b|_)/i },
	// { name: '世纪天元', rule: /\bCTYON(?:\b|_)/i },
	// { name: '神舟', rule: /\bHasee(?:\b|_)/i },
	// { name: '爱我', rule: /\bLovme(?:\b|_)/i },
	// { name: '美富通', rule: /\bMOFUT(?:\b|_)/ },
	// { name: '摩乐', rule: /\bMOLOO(?:\b|_)/ },
	// { name: '为美', rule: /\bVIMOO(?:\b|_)/i },
	// { name: '普莱达', rule: /\bPULID(?:\b|_)/i },
	// { name: '誉品', rule: /\bYEPEN\b/ },
	// { name: '京崎', rule: /\bTOOKY\b/ },
	// { name: '华录', rule: /\bHualu(?:\b|_)/ },
	// { name: '英特奇', rule: /\b(?:[Ii]ntki|INTKI)(?:\b|_|[A-Z]\d+\b)/ },
	// { name: '雷萨', rule: /\bLEISA(?:\b|_)/ },
	// { name: '美莱仕', rule: /\bMlais(?:\b|_)/ },
	{ name: '步步高', rule: /\bvivo(?:\b|_)/i },
	{ name: '波导', rule: /\bBird(?:\b|_)/i },
	{ name: '索尼', rule: /\b(?:Sony|Xperia)(?:\b|_)/i },
	{ name: '亿通', rule: /\bETON(?:\b|_)/ },
	{ name: '朵唯', rule: /\bDOOV(?:\b|_)/ },
	// { name: '米歌', rule: /\bMEEG(?:\b|_)/ },
	// { name: '先科', rule: /\bSAST\b/ },
	// { name: '夏新', rule: /\bAMOI(?:\b|_)/ },
	// { name: '欧奇', rule: /\bOUKI(?:\b|_)/ },
	// { name: '欧比', rule: /\bOBEE(?:\b|_)/ },
	// { name: '昂达', rule: /\bONDA(?:\b|_)/ },
	// { name: '宏为', rule: /\bHOOW(?:\b|_)/ },
	// { name: '羽翼', rule: /\bYUYI\b/ },
	// { name: '传奇', rule: /\bSAGA(?:\b|_)/ },
	// { name: '七喜', rule: /\bHEDY(?:\b|_)/ },
	// { name: '世纪星', rule: /\bTETC\b/ },
	// { name: '联合时代', rule: /\bUTime(?:\b|_)/ },
	// { name: '戴尔', rule: /\b(?:Dell|Streak|Venue\d*)(?:\b|_)/i },
	// { name: '华硕', rule: /\b(?:ASUS|PadFone)(?:\b|_)/i },
	{ name: 'OPPO', rule: /\boppo(?:\b|_|[A-Z])/i },
	{ name: 'OPPO', rule: /\bOPPO[A-Z0-9]{2,5}\b/ },
	// { name: 'VOTO', rule: /\bVOTO(?:\b|_)/ },
	// { name: '铂锐', rule: /\bBROR(?:\b|_)/ },
	// { name: '亿美', rule: /\bEOOM(?:\b|_)/ },
	// { name: '奥乐', rule: /\bAOLE(?:\b|_)/ },
	// { name: '酷比魔方', rule: /\bCUBE\b/ },
	// { name: '玉科', rule: /\bYUKE\b/ },
	// { name: 'E人E本', rule: /\bEBEN\b/ },
	// { name: '铂瓷', rule: /\bBOHP(?:\b|_)/i },
	{ name: '步步高', rule: /\bBBK\b/ },
	// { name: 'ThL', rule: /\bThL(?:\b|_)/i },
	{ name: 'TCL', rule: /\bTCL(?:[A-Z]\d{3})?(?:\b|_)/ },
	{ name: '中兴', rule: /\bZTE(?:\b|_)/ },
	// { name: '奥克斯', rule: /\bAUX(?:\b|_)/ },
	// { name: '锋达通', rule: /\bFDT(?:\b|_)/ },
	// { name: '港利通', rule: /\bKPT(?:\b|_)/ },
	// { name: '黑米', rule: /\bHMI(?:\b|_)/ },
	// { name: '黑米', rule: /\bHMIA\d\b/ },
	// { name: '高新奇', rule: /\bGXQ(?:\b|_)/ },
	// { name: '赛博宇华', rule: /\bSOP\b/ },
	// { name: '百分百', rule: /\bBFB(?:\b|_)/ },
	{ name: 'LG', rule: /\b(?:LG|Optimus)(?:\b|_)/i },
	{ name: '索尼', rule: /\bSonyEricsson/i },
	{ name: '金立', rule: /\b(?:GiONEE|EENOiG)/i },
	// { name: '飞利浦', rule: /\bPhilips/ },
	// { name: '先锋', rule: /\bPioneer/ },
	// { name: '至尊宝', rule: /\b(?:Bestsonny|Best\ssonny)/i },
	// { name: '长虹', rule: /\bChanghong/i },
	{ name: '酷派', rule: /\bCoolpad/i },
	{ name: '华为', rule: /\bHUAWEI/i },
	// { name: '天迈', rule: /\bT-smart/ },
	// { name: '美图', rule: /\bMeitu/ },
	// { name: '蓝魔', rule: /\bRamos/i },
	// { name: '欧新', rule: /\b(?:HOSIN|Hosin)/ },
	{ name: '索尼', rule: /\bSony[A-Z]/ },
	{ name: 'HTC', rule: /\bHTC/ },
	{ name: '华为', rule: /\b(?:HONOR|Ascend|IDEOS)(?:\b|_)/i },
	{ name: '联想', rule: /\bLenovo/i },
	{ name: '联想', rule: /\bIdea(?:pad|Tab)/ },
	{ name: '诺基亚', rule: /\bNokia/ },
	{ name: '康佳', rule: /\bKonka/i },
	// { name: '语信', rule: /\bSUN/i },
	{ name: 'HTC', rule: /\b(?:Desire|Sensation|Incredible)(?:\b|_)/ },
	{ name: '摩托罗拉', rule: /\b(?:Milestone|Xoom|DROID[A-Z0-9]?|Droid\d?|Defy)\b/ },
	{ name: '波导', rule: /\bDoeasy(?:\b|_)/i },
	{ name: 'Google', rule: /\bNexus(?:\b|_|\d)/i },
	// { name: '普耐尔', rule: /\bMOMO(?:\b|_|\d)/i },
	{ name: '小米', rule: /\bMI(?:-ONE|\sPad)/ },
	{ name: '小米', rule: /\b(?:MI|Mi|HM)[\s_-][A-Za-z0-9]+\b/ },
	{ name: '小米', rule: /\b(?:MI|Mi|HM)\d[A-Z]?\b/ },
	{ name: '小米', rule: /\bBuild\/HM\d{7}\b/ },
	{ name: '小米', rule: /\bMi\s?\d\b/ },
	{ name: '小米', rule: /\bHONGMI/i },
	// { name: '欧奇', rule: /\b(?:OK[AU]|okA)\d+[A-Z]*\b/ },
	{ name: 'OPPO', rule: /\bFind\s?\d+\b/i },
	{ name: '三星', rule: /\bS(?:M|[CGP]H)-[A-Za-z0-9]+\b/ },
	{ name: '三星', rule: /\bSC-\d{2}[A-Z]\b/ },
	{ name: '三星', rule: /\bSHV-/ },
	{ name: '三星', rule: /\bSHW-/ },
	{ name: '三星', rule: /\bGT[-_][A-Z][A-Z0-9]{3,}\b/i },
	{ name: '摩托罗拉', rule: /\bMOT-/ },
	{ name: 'LG', rule: /\bLG[A-Z]+\d+\b/ },
	{ name: '小辣椒', rule: /\bLA\d?-[A-Z0-9]+\b/ },
	{ name: '小辣椒', rule: /\bLA\d[A-Z]\b/ },
	{ name: 'HTC', rule: /\bHTL\d{2}\b/ },
	{ name: '中兴', rule: /\bZTE[A-Z]\d+[A-Za-z]*\d*(?:_[A-Z]+)?\b/ },
	// { name: '优米', rule: /\bUMI(?:\b|_|\d)/ },
	{ name: '康佳', rule: /\bKON-EG?\d+\b/ },
	{ name: '海信', rule: /\bHS(?:\b|_)/ },
	// { name: '泛泰', rule: /\bIM-/ },
	{ name: '海尔', rule: /\bHT-[A-Z0-9]+\b/ },
	// { name: '贝尔丰', rule: /\bBF(?:\b|_|\d+\b)/ },
	// { name: '沃普丰', rule: /\bWPF?(?:\b|_)/ },
	{ name: '摩托罗拉', rule: /;\sM[BTE][5-9]\d{2}\b/ },
	{ name: '摩托罗拉', rule: /;\sMZ6\d{2}\b/ },
	{ name: '摩托罗拉', rule: /;\sXT(?:\d{4}|\d{3}[A-Z]?)\b/ },
	{ name: '索尼', rule: /;\sL[1-9]\d[a-zA-Z]\b/ },
	{ name: '索尼', rule: /;\sLT\d{2}[a-z]{0,2}\b/ },
	{ name: '索尼', rule: /;\sST\d{2}[a-z]\b/ },
	{ name: '索尼', rule: /;\sS55[tu]\b/ },
	{ name: '索尼', rule: /;\s[MW]T\d+i\b/ },
	{ name: '索尼', rule: /;\sSK\d{2}i\b/ },
	{ name: '索尼', rule: /;\sM\d{2}[cw]\b/ },
	{ name: '索尼', rule: /;\sX[ML]\d+[a-z]?\b/ },
	{ name: '索尼', rule: /;\sX\d{2}[a-z]\b/ },
	{ name: '索尼', rule: /;\sS\d{2}h\b/ },
	{ name: '索尼', rule: /;\sM\d{2}[th]\b/ },
	{ name: '索尼', rule: /;\sC6[689]\d{2}\b/ },
	{ name: '索尼', rule: /;\sC1[569]0[45]\b/ },
	{ name: '索尼', rule: /;\sC2[013]0[45]\b/ },
	// { name: '索尼', rule: /;\sE15i\b/ },
	{ name: '华为', rule: /;\sH\d{2}-[A-Z]\d{2}\b/ },
	{ name: '金立', rule: /;\s(?:GN\d{3,}[A-Z]?)\b/ },
	{ name: '金立', rule: /;\sX8(?:05|17)\b/ },
	{ name: 'OPPO', rule: /;\sX90\dT?\b/ },
	{ name: 'OPPO', rule: /;\sU7\d{2}[WT]\b/ },
	{ name: 'OPPO', rule: /;\sR8\d{2}[A-Za-z]?\b/ },
	{ name: 'OPPO', rule: /;\sR\d{4}\b/ },
	{ name: 'OPPO', rule: /;\sX90[07]7\b/ },
	{ name: 'OPPO', rule: /;\sN5117\b/ },
	// { name: '华硕', rule: /;\sME\d{3}[A-Z]{1,2}\b/ },
	// { name: '奥洛斯', rule: /;\sAE(?:\b|_|\d+\b)/ },
	{ name: '中兴', rule: /;\sNX\d{2,}[A-Z]?\b/ },
	{ name: '中兴', rule: /;\sV9\d{3}\b/ },
	{ name: '中兴', rule: /;\s[NU]9180\b/ },
	{ name: '金立', rule: /;\sV18[25]\b/ },
	{ name: '金立', rule: /;\sE[2-9](?:mini|[A-Z])?\b/ },
	// { name: '广信', rule: /;\sEF\d+[A-Z]*\b/ },
	// { name: '先锋', rule: /;\sE[78]1t\b/ },
	// { name: '先锋', rule: /;\s(?:E91w|P80w)\b/ },
	// { name: '酷比魔方', rule: /;\sU\d+GT[A-Z0-9]*(?:\b|_)/ },
	// { name: '台电', rule: /;\sP8[589][ast]?(?:mini)?\b/ },
	// { name: '台电', rule: /;\sP7[0568][aehstv]\b/ },
	// { name: '台电', rule: /;\sG17[sh]?\b/ },
	// { name: '台电', rule: /;\sG18d?(?:\s?mini)?\b/ },
	// { name: '台电', rule: /;\sA\d{2}HD\b/ },
	{ name: '魅族', rule: /;\sM(?:030|031|032|040|045|351|353|355|356|460|461)\b/ },
	{ name: 'TCL', rule: /;\sJ\d{3}[DT]\b/ },
	// { name: '奥克斯', rule: /;\sV9\d{2}[ABDPTW]{1,2}\b/ },
	// { name: '昂达', rule: /;\sV[7-9]\d{2}(?:[a-z]|mini)\b/ },
	// { name: '昂达', rule: /;\sP\d{2}HD\b/i },
	// { name: '聆韵', rule: /;\sU9[1-9]0[ABCT]\b/ },
	{ name: '波导', rule: /;\sT9[56]0[08]\b/ },
	{ name: '波导', rule: /;\sT910[58]\b/ },
	{ name: '中国移动', rule: /;\sM(?:601|701|811)\b/ }
	// { name: '酷派', rule: /;\s[5789]\d{3}[a-z]?\b/i }
];

exports.exec = function(ua) {
	var result, osResult = os.exec(ua);
	if ( os.isPC(osResult) ) {
		result = {
			name: 'PC',
			version: 'Others'
		};
	} else if ( osResult.name === 'iOS' ) {
		result = util.execRules(ua, appleRules);
	} else {
		result = util.execRules(ua, otherRules);
	}
	result.type = 'devicebrand';
	return result;
};